# Generated by Django 5.1.1 on 2024-10-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
